version: 2
jobs:
  build-backend:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build backend Docker image
          command: |
            gradle build
            docker build -t repo.treescale.com/${TREESCALE_USER}/hackyeah:2019 .
      - deploy:
          name: Push app docker image to registry
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login --username=${TREESCALE_USER} -p ${TREESCALE_PASS} repo.treescale.com
              docker push repo.treescale.com/${TREESCALE_USER}/hackyeah:2019
            fi
  build-frontend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run:
          name: Change folder to 'frontend'
          command: cd frontend
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build frontend Docker image
          command: |
            cd frontend
            docker build -t repo.treescale.com/${TREESCALE_USER}/hackyeah:2019-front .
      - deploy:
          name: Push app docker image to registry
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login --username=${TREESCALE_USER} -p ${TREESCALE_PASS} repo.treescale.com
              docker push repo.treescale.com/${TREESCALE_USER}/hackyeah:2019-front
            fi
workflows:
  version: 2
  build:
    jobs:
      - build-backend
      - build-frontend